name: Boomers of Memory CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive # If we ever add any submodules

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential valgrind libcunit1 libcunit1-dev

    - name: Build
      run: make all

    - name: Run tests
      run: make test

    - name: Run tests with Valgrind
      run: make memtest

